# Generated by Django 3.2.5 on 2021-07-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'STUDENT'), ('teacher', 'TEACHER')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.IntegerField(default=6000000000),
            preserve_default=False,
        ),
    ]
