# Generated by Django 3.2.5 on 2021-07-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210706_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'STUDENT'), ('teacher', 'TEACHER')], default='student', max_length=10, null=True),
        ),
    ]
