# Generated by Django 3.2.5 on 2021-07-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_class_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.CharField(default=0, max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='ta',
            field=models.CharField(default=0, max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.CharField(default=0, max_length=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(default='default_classroom.jpeg', upload_to='class_pics'),
        ),
    ]
