# Generated by Django 3.2.5 on 2021-07-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20210706_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='student',
            field=models.CharField(default=0, max_length=100000),
        ),
        migrations.AlterField(
            model_name='class',
            name='ta',
            field=models.CharField(default=0, max_length=100000),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.CharField(default=0, max_length=100000),
        ),
    ]
