# Generated by Django 3.2.5 on 2021-07-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20210707_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(default='default_classroom.png', upload_to='class_pics'),
        ),
    ]
